version: '3.9'

services:
  order-service:
    image: paycore-order:latest
    container_name: order-service
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - order-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-postgres:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=orderuser
      - SPRING_DATASOURCE_PASSWORD=orderpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  order-outbox-worker:
    image: order-outbox-worker:latest
    container_name: order-outbox-worker
    build:
      context: ./order-outbox-worker
      dockerfile: Dockerfile
    ports:
      - "9081:9081"
    depends_on:
      - order-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=9081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-postgres:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=orderuser
      - SPRING_DATASOURCE_PASSWORD=orderpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - POSTGRESQL_HOST=order-postgres

  order-postgres:
    image: postgres:16
    container_name: order-postgres
    restart: always
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=orderuser
      - POSTGRES_PASSWORD=orderpass
    command:
      - postgres
      - -c
      - wal_level=logical # logical decoding requires wal_level >= logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10
    ports:
      - "5433:5432"
    volumes:
      - order_pgdata:/var/lib/postgresql/data

  payment-service:
    image: paycore-payment:latest
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - payment-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-postgres:5432/paymentdb
      - SPRING_DATASOURCE_USERNAME=paymentuser
      - SPRING_DATASOURCE_PASSWORD=paymentpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  payment-postgres:
    image: postgres:16
    container_name: payment-postgres
    restart: always
    environment:
      - POSTGRES_DB=paymentdb
      - POSTGRES_USER=paymentuser
      - POSTGRES_PASSWORD=paymentpass
    ports:
      - "5434:5432"
    volumes:
      - payment_pgdata:/var/lib/postgresql/data

  notification-service:
    image: paycore-notification:latest
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - notification-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://notification-postgres:5432/notificationdb
      - SPRING_DATASOURCE_USERNAME=notificationuser
      - SPRING_DATASOURCE_PASSWORD=notificationpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  notification-postgres:
    image: postgres:16
    container_name: notification-postgres
    restart: always
    environment:
      - POSTGRES_DB=notificationdb
      - POSTGRES_USER=notificationuser
      - POSTGRES_PASSWORD=notificationpass
    ports:
      - "5435:5432"
    volumes:
      - notification_pgdata:/var/lib/postgresql/data

  settlement-service:
    image: paycore-settlement:latest
    container_name: settlement-service
    build:
      context: ./settlement-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - settlement-postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:postgresql://settlement-postgres:5432/settlementdb
      - SPRING_DATASOURCE_USERNAME=settlementuser
      - SPRING_DATASOURCE_PASSWORD=settlementpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  settlement-postgres:
    image: postgres:16
    container_name: settlement-postgres
    restart: always
    environment:
      - POSTGRES_DB=settlementdb
      - POSTGRES_USER=settlementuser
      - POSTGRES_PASSWORD=settlementpass
    ports:
      - "5436:5432"
    volumes:
      - settlement_pgdata:/var/lib/postgresql/data

volumes:
  order_pgdata:
  payment_pgdata:
  notification_pgdata:
  settlement_pgdata:
