global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8081']

  - job_name: 'order-outbox-worker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-outbox-worker:9081']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8082']

  - job_name: 'payment-outbox-worker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-outbox-worker:9082']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8083']

  - job_name: 'settlement-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['settlement-service:8084']
